spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: booking
    password: booking
  flyway:
    enabled: true
  management:
    endpoint:
      health:
        show-details: always
    health:
      db:
        enabled: true